import Head from "next/head";

export default function Home() {
  return (
    <div className="w-full h-[100vh] bg-green-500">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <span>First page!!!</span>
    </div>
  );
}
