import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { signIn } from "next-auth/react";

export default function Home() {
  const handleSubmit = async (e) => {
    e.preventDefault();

    const formData = new FormData(e.target);
    const formEntries = Object.fromEntries(formData.entries());

    const { username, password } = formEntries;
    console.log(username, password);

    // const res = await signIn("credentials", {
    //   redirect: false,
    //   username: username.replace(/\s/g, "").trim(),
    //   password: password.trim(),
    // });

    // console.log(res);

    try {
      const response = await axios.post("/api/createUser", formEntries);
      console.log(response.data);
    } catch (error) {
      console.log(error);
      console.log(error.response.data.message);
    }
  };
  return (
    <div className={styles.container}>
      <form onSubmit={handleSubmit}>
        <input type="text" name="username" />
        <input type="text" name="password" />
        <button type="submit">Sumbit</button>
      </form>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <span>First page!!!</span>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
